#!/bin/sh
set +v
echo "######################### WARNING #########################"
echo "  This package will run a test browser on which you will"
echo "  have to try some of the sites you plan to use the most."
echo " In order to provide better profiling, you should run this"
echo "  test for as long as you can. Make sure you have xauth"
echo "       correctly set up before starting this build."
echo "     Additionally, you can specify which user you wish"
echo "      to run the browser as, for added practicality."
echo "###########################################################"
read -s -p "Press enter to continue"
set -v
